### ISSUE TITLE
When I used the pug, I found out that the document was in discrepancy, whether I had a problem with it.

### ISSUE THREAD

**Issue by MiYogurt** [pugjs/constantinople#6]
this is document 

![image](https://user-images.githubusercontent.com/10082395/37568684-b568fff0-2b13-11e8-9b5f-b71c193d0510.png)

my test file `a.js`

```js
const md = require("jstransformer")(require("jstransformer-markdown-it"));
const { resolve } = require("path");
const FS = require("fs");

console.log(md.render("# hello"));
console.log(md.renderFile("./a.md"));

const pug = require("pug");
const source = `
p some ss #[:md(inline='true') # hello]

include:md /a.md
`;
var html = pug.compile(source, {
  basedir: __dirname,
  filters: {
    md: (text, opts) => {
      console.log(opts);
      if (opts.inline) {
        return md.render(text).body;
      }
      if (opts.filename) {
        return md.renderFile(opts.filename).body;
      }
    }
  }
});

console.log(html());
```

![image](https://user-images.githubusercontent.com/10082395/37568703-0384a0a4-2b14-11e8-8b5c-d46ba45db4d5.png)

it's work , i use string ‘true’ bypass  `constantinople` logic 。 when i use `#[:md(inline) # hello]`

i got an error `true is not constant. All filters are rendered compile-time so filter options must be constants`

![image](https://user-images.githubusercontent.com/10082395/37568750-5d301a7a-2b14-11e8-9f7b-623184318961.png)

when i use `include:md ./a.md` or `include:md a.md`   

![image](https://user-images.githubusercontent.com/10082395/37568762-87341718-2b14-11e8-9727-79ee2390889e.png)

i read the error source code , find the path need start with '/' so ，i add '/' bypass the logic。

did have something config let my code keep with document? 3q~ 🙏

**Comment by ForbesLindesay** [comment]
```diff
 var html = pug.compile(source, {
   basedir: __dirname,
+  filename: __filename,
   filters: {
     md: (text, opts) => {
       console.log(opts);
       if (opts.inline) {
         return md.render(text).body;
       }
       if (opts.filename) {
         return md.renderFile(opts.filename).body;
       }
     }
   }
 });
```

As the error says, if the path in `include` is relative, you must specify the `filename` option. When you use `compileFileClient`, `compileFile` or `renderFile`, the `filename` option is added automatically for you.
