### ISSUE TITLE
server deployments require `core-js`

### ISSUE THREAD

**Issue by zackschuster** [pugjs/constantinople#8]
...entirely because of the `babylon`/`babel-type` dependencies. this adds a not-inconsiderable amount of needless runtime bloat that's quite painful to e.g. FTP deploy `node_modules`, even with mechanisms like `.yarnclean` to soften the blow.

you can see just how much the package bloated since the switch [on packagephobia](https://packagephobia.now.sh/result?p=constantinople@3.1.2). it's quite the jump.

the [original PR](https://github.com/pugjs/constantinople/pull/4) mentioned it was so people could "get the latest JS features", but that was almost 3 years ago & things have changed substantially since then.

as other parts of the pug tree already rely on `acorn` -- which is zero dependency & doesn't suffer from these issues as a result -- i would seriously recommend at the very least evaluating if returning to `acorn` is viable. 

i would be willing to contribute work here.

**Comment by ForbesLindesay** [comment]
This isn't likely to be a priority any time soon I'm afraid.

**Comment by zackschuster** [comment]
if i made it a priority for myself & contributed a PR, would i have good odds of getting it merged?

**Comment by ForbesLindesay** [comment]
I'd much rather we push babylon/babel-types to see if they can drop the core-js dependency. I doubt it's really necessary in a world of modern JavaScript.

**Comment by jonathansamines** [comment]
@zackschuster @ForbesLindesay Newest versions (v7) of babylon (@babel/parser@7) and @babel/types@7 seems to be no longer depending on core-js. Could an update of those dependencies help to solve this issue?

**Comment by ForbesLindesay** [comment]
I'd gladly accept a PR for that.

**Comment by zackschuster** [comment]
submitted #9

**Comment by ForbesLindesay** [comment]
This is now resolved in 4.0.1
